version: 2

updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"

    # Maintain dependencies for Composer
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"

    # Maintain dependencies for PHP CS Fixer
    - package-ecosystem: "composer"
      directory: "/tools/php-cs-fixer/"
      schedule:
          interval: "weekly"

    # Maintain dependencies for PHPStan
    - package-ecosystem: "composer"
      directory: "/tools/phpstan/"
      schedule:
          interval: "weekly"

    # Maintain dependencies for Twig CS Fixer
    - package-ecosystem: "composer"
      directory: "/tools/twig-cs-fixer/"
      schedule:
          interval: "weekly"
